sonar.projectKey=C0dingViking_soen390-mini-capstone
sonar.organization=c0dingviking

sonar.projectName=soen390-mini-capstone
sonar.projectVersion=1.0

# The CI sets 'concordia_campus_guide' as the current working directory, hence paths should be relative to that
sonar.sources=lib
sonar.tests=test
sonar.dart.lcov.reportPaths=coverage/lcov.info
# Exclude home_screen.dart from analysis since it can only properly be tested w/ E2E tests
sonar.exclusions=lib/ui/home/widgets/home_screen.dart

sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io
