// Mocks generated by Mockito 5.4.6 from annotations
// in concordia_campus_guide/test/ui/hamburger_menu/widgets/hamburger_menu_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i11;

import 'package:concordia_campus_guide/domain/interactors/directions_interactor.dart' as _i6;
import 'package:concordia_campus_guide/domain/interactors/map_data_interactor.dart' as _i4;
import 'package:concordia_campus_guide/domain/interactors/places_interactor.dart' as _i5;
import 'package:concordia_campus_guide/domain/models/academic_class.dart' as _i18;
import 'package:concordia_campus_guide/domain/models/building.dart' as _i13;
import 'package:concordia_campus_guide/domain/models/coordinate.dart' as _i17;
import 'package:concordia_campus_guide/domain/models/route_option.dart' as _i15;
import 'package:concordia_campus_guide/domain/models/search_suggestion.dart' as _i16;
import 'package:concordia_campus_guide/ui/auth/view_models/login_view_model.dart' as _i10;
import 'package:concordia_campus_guide/ui/home/view_models/home_view_model.dart' as _i12;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart' as _i2;
import 'package:firebase_core/firebase_core.dart' as _i7;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i14;
import 'package:google_sign_in/google_sign_in.dart' as _i19;
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart' as _i20;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserMetadata_0 extends _i1.SmartFake implements _i2.UserMetadata {
  _FakeUserMetadata_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeMultiFactor_1 extends _i1.SmartFake implements _i3.MultiFactor {
  _FakeMultiFactor_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeIdTokenResult_2 extends _i1.SmartFake implements _i2.IdTokenResult {
  _FakeIdTokenResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_3 extends _i1.SmartFake implements _i3.UserCredential {
  _FakeUserCredential_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_4 extends _i1.SmartFake implements _i3.ConfirmationResult {
  _FakeConfirmationResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_5 extends _i1.SmartFake implements _i3.User {
  _FakeUser_5(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeMapDataInteractor_6 extends _i1.SmartFake implements _i4.MapDataInteractor {
  _FakeMapDataInteractor_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlacesInteractor_7 extends _i1.SmartFake implements _i5.PlacesInteractor {
  _FakePlacesInteractor_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectionsInteractor_8 extends _i1.SmartFake implements _i6.DirectionsInteractor {
  _FakeDirectionsInteractor_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_9 extends _i1.SmartFake implements _i7.FirebaseApp {
  _FakeFirebaseApp_9(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeActionCodeInfo_10 extends _i1.SmartFake implements _i2.ActionCodeInfo {
  _FakeActionCodeInfo_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePasswordValidationStatus_11 extends _i1.SmartFake
    implements _i2.PasswordValidationStatus {
  _FakePasswordValidationStatus_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i3.User {
  @override
  bool get emailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#emailVerified),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(
            Invocation.getter(#isAnonymous),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_0(this, Invocation.getter(#metadata)),
            returnValueForMissingStub: _FakeUserMetadata_0(this, Invocation.getter(#metadata)),
          )
          as _i2.UserMetadata);

  @override
  List<_i2.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i2.UserInfo>[],
            returnValueForMissingStub: <_i2.UserInfo>[],
          )
          as List<_i2.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#uid)),
            returnValueForMissingStub: _i8.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  _i3.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_1(this, Invocation.getter(#multiFactor)),
            returnValueForMissingStub: _FakeMultiFactor_1(this, Invocation.getter(#multiFactor)),
          )
          as _i3.MultiFactor);

  @override
  _i9.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i9.Future<String?>.value(),
            returnValueForMissingStub: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<_i2.IdTokenResult> getIdTokenResult([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i9.Future<_i2.IdTokenResult>.value(
              _FakeIdTokenResult_2(this, Invocation.method(#getIdTokenResult, [forceRefresh])),
            ),
            returnValueForMissingStub: _i9.Future<_i2.IdTokenResult>.value(
              _FakeIdTokenResult_2(this, Invocation.method(#getIdTokenResult, [forceRefresh])),
            ),
          )
          as _i9.Future<_i2.IdTokenResult>);

  @override
  _i9.Future<_i3.UserCredential> linkWithCredential(_i2.AuthCredential? credential) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#linkWithCredential, [credential])),
            ),
            returnValueForMissingStub: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#linkWithCredential, [credential])),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<_i3.UserCredential> linkWithProvider(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#linkWithProvider, [provider])),
            ),
            returnValueForMissingStub: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#linkWithProvider, [provider])),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<_i3.UserCredential> reauthenticateWithProvider(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<_i3.UserCredential> reauthenticateWithPopup(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#reauthenticateWithPopup, [provider])),
            ),
            returnValueForMissingStub: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#reauthenticateWithPopup, [provider])),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<void> reauthenticateWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.UserCredential> linkWithPopup(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#linkWithPopup, [provider])),
            ),
            returnValueForMissingStub: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#linkWithPopup, [provider])),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<void> linkWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i3.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i9.Future<_i3.ConfirmationResult>.value(
              _FakeConfirmationResult_4(
                this,
                Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i3.ConfirmationResult>.value(
              _FakeConfirmationResult_4(
                this,
                Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
              ),
            ),
          )
          as _i9.Future<_i3.ConfirmationResult>);

  @override
  _i9.Future<_i3.UserCredential> reauthenticateWithCredential(_i2.AuthCredential? credential) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
            returnValueForMissingStub: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> sendEmailVerification([_i2.ActionCodeSettings? actionCodeSettings]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i9.Future<_i3.User>.value(
              _FakeUser_5(this, Invocation.method(#unlink, [providerId])),
            ),
            returnValueForMissingStub: _i9.Future<_i3.User>.value(
              _FakeUser_5(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i9.Future<_i3.User>);

  @override
  _i9.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updatePhoneNumber(_i2.PhoneAuthCredential? phoneCredential) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {#displayName: displayName, #photoURL: photoURL}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i2.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [newEmail, actionCodeSettings]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [LoginViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginViewModel extends _i1.Mock implements _i10.LoginViewModel {
  MockLoginViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSignedIn =>
      (super.noSuchMethod(Invocation.getter(#isSignedIn), returnValue: false) as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false) as bool);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() =>
      super.noSuchMethod(Invocation.method(#dispose, []), returnValueForMissingStub: null);

  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []), returnValueForMissingStub: null);
}

/// A class which mocks [HomeViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeViewModel extends _i1.Mock implements _i12.HomeViewModel {
  MockHomeViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MapDataInteractor get mapInteractor =>
      (super.noSuchMethod(
            Invocation.getter(#mapInteractor),
            returnValue: _FakeMapDataInteractor_6(this, Invocation.getter(#mapInteractor)),
          )
          as _i4.MapDataInteractor);

  @override
  _i5.PlacesInteractor get placesInteractor =>
      (super.noSuchMethod(
            Invocation.getter(#placesInteractor),
            returnValue: _FakePlacesInteractor_7(this, Invocation.getter(#placesInteractor)),
          )
          as _i5.PlacesInteractor);

  @override
  _i6.DirectionsInteractor get directionsInteractor =>
      (super.noSuchMethod(
            Invocation.getter(#directionsInteractor),
            returnValue: _FakeDirectionsInteractor_8(
              this,
              Invocation.getter(#directionsInteractor),
            ),
          )
          as _i6.DirectionsInteractor);

  @override
  bool get showLoginSuccessMessage =>
      (super.noSuchMethod(Invocation.getter(#showLoginSuccessMessage), returnValue: false) as bool);

  @override
  Map<String, _i13.Building> get buildings =>
      (super.noSuchMethod(Invocation.getter(#buildings), returnValue: <String, _i13.Building>{})
          as Map<String, _i13.Building>);

  @override
  Set<_i14.Polygon> get buildingOutlines =>
      (super.noSuchMethod(Invocation.getter(#buildingOutlines), returnValue: <_i14.Polygon>{})
          as Set<_i14.Polygon>);

  @override
  Set<_i14.Marker> get buildingMarkers =>
      (super.noSuchMethod(Invocation.getter(#buildingMarkers), returnValue: <_i14.Marker>{})
          as Set<_i14.Marker>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false) as bool);

  @override
  bool get isSearchingPlaces =>
      (super.noSuchMethod(Invocation.getter(#isSearchingPlaces), returnValue: false) as bool);

  @override
  bool get isResolvingPlace =>
      (super.noSuchMethod(Invocation.getter(#isResolvingPlace), returnValue: false) as bool);

  @override
  bool get isResolvingStartLocation =>
      (super.noSuchMethod(Invocation.getter(#isResolvingStartLocation), returnValue: false)
          as bool);

  @override
  bool get isLoadingRoutes =>
      (super.noSuchMethod(Invocation.getter(#isLoadingRoutes), returnValue: false) as bool);

  @override
  Map<_i15.RouteMode, _i15.RouteOption> get routeOptions =>
      (super.noSuchMethod(
            Invocation.getter(#routeOptions),
            returnValue: <_i15.RouteMode, _i15.RouteOption>{},
          )
          as Map<_i15.RouteMode, _i15.RouteOption>);

  @override
  _i15.RouteMode get selectedRouteMode =>
      (super.noSuchMethod(
            Invocation.getter(#selectedRouteMode),
            returnValue: _i15.RouteMode.walking,
          )
          as _i15.RouteMode);

  @override
  Set<_i14.Polyline> get routePolylines =>
      (super.noSuchMethod(Invocation.getter(#routePolylines), returnValue: <_i14.Polyline>{})
          as Set<_i14.Polyline>);

  @override
  Set<_i14.Circle> get transitChangeCircles =>
      (super.noSuchMethod(Invocation.getter(#transitChangeCircles), returnValue: <_i14.Circle>{})
          as Set<_i14.Circle>);

  @override
  bool get showNextClassFab =>
      (super.noSuchMethod(Invocation.getter(#showNextClassFab), returnValue: false) as bool);

  @override
  bool get showNextClassDialog =>
      (super.noSuchMethod(Invocation.getter(#showNextClassDialog), returnValue: false) as bool);

  @override
  _i12.DepartureMode get departureMode =>
      (super.noSuchMethod(Invocation.getter(#departureMode), returnValue: _i12.DepartureMode.now)
          as _i12.DepartureMode);

  @override
  List<_i16.SearchSuggestion> get searchResults =>
      (super.noSuchMethod(Invocation.getter(#searchResults), returnValue: <_i16.SearchSuggestion>[])
          as List<_i16.SearchSuggestion>);

  @override
  bool get myLocationEnabled =>
      (super.noSuchMethod(Invocation.getter(#myLocationEnabled), returnValue: false) as bool);

  @override
  bool get isSearchBarExpanded =>
      (super.noSuchMethod(Invocation.getter(#isSearchBarExpanded), returnValue: false) as bool);

  @override
  int get unfocusSearchBarSignal =>
      (super.noSuchMethod(Invocation.getter(#unfocusSearchBarSignal), returnValue: 0) as int);

  @override
  List<_i17.Coordinate> get campuses =>
      (super.noSuchMethod(Invocation.getter(#campuses), returnValue: <_i17.Coordinate>[])
          as List<_i17.Coordinate>);

  @override
  int get selectedCampusIndex =>
      (super.noSuchMethod(Invocation.getter(#selectedCampusIndex), returnValue: 0) as int);

  @override
  Set<_i14.Marker> get mapMarkers =>
      (super.noSuchMethod(Invocation.getter(#mapMarkers), returnValue: <_i14.Marker>{})
          as Set<_i14.Marker>);

  @override
  set buildings(Map<String, _i13.Building>? value) =>
      super.noSuchMethod(Invocation.setter(#buildings, value), returnValueForMissingStub: null);

  @override
  set buildingOutlines(Set<_i14.Polygon>? value) => super.noSuchMethod(
    Invocation.setter(#buildingOutlines, value),
    returnValueForMissingStub: null,
  );

  @override
  set buildingMarkers(Set<_i14.Marker>? value) => super.noSuchMethod(
    Invocation.setter(#buildingMarkers, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentBuilding(_i13.Building? value) => super.noSuchMethod(
    Invocation.setter(#currentBuilding, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(bool? value) =>
      super.noSuchMethod(Invocation.setter(#isLoading, value), returnValueForMissingStub: null);

  @override
  set errorMessage(String? value) =>
      super.noSuchMethod(Invocation.setter(#errorMessage, value), returnValueForMissingStub: null);

  @override
  set generateInfoMessage(String? value) =>
      super.noSuchMethod(Invocation.setter(#infoMessage, value), returnValueForMissingStub: null);

  @override
  set isSearchingPlaces(bool? value) => super.noSuchMethod(
    Invocation.setter(#isSearchingPlaces, value),
    returnValueForMissingStub: null,
  );

  @override
  set isResolvingPlace(bool? value) => super.noSuchMethod(
    Invocation.setter(#isResolvingPlace, value),
    returnValueForMissingStub: null,
  );

  @override
  set isResolvingStartLocation(bool? value) => super.noSuchMethod(
    Invocation.setter(#isResolvingStartLocation, value),
    returnValueForMissingStub: null,
  );

  @override
  set searchStartMarker(_i14.Marker? value) => super.noSuchMethod(
    Invocation.setter(#searchStartMarker, value),
    returnValueForMissingStub: null,
  );

  @override
  set searchDestinationMarker(_i14.Marker? value) => super.noSuchMethod(
    Invocation.setter(#searchDestinationMarker, value),
    returnValueForMissingStub: null,
  );

  @override
  set startCoordinate(_i17.Coordinate? value) => super.noSuchMethod(
    Invocation.setter(#startCoordinate, value),
    returnValueForMissingStub: null,
  );

  @override
  set destinationCoordinate(_i17.Coordinate? value) => super.noSuchMethod(
    Invocation.setter(#destinationCoordinate, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedStartLabel(String? value) => super.noSuchMethod(
    Invocation.setter(#selectedStartLabel, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedDestinationLabel(String? value) => super.noSuchMethod(
    Invocation.setter(#selectedDestinationLabel, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingRoutes(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingRoutes, value),
    returnValueForMissingStub: null,
  );

  @override
  set routeErrorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#routeErrorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  set routeOptions(Map<_i15.RouteMode, _i15.RouteOption>? value) =>
      super.noSuchMethod(Invocation.setter(#routeOptions, value), returnValueForMissingStub: null);

  @override
  set selectedRouteMode(_i15.RouteMode? value) => super.noSuchMethod(
    Invocation.setter(#selectedRouteMode, value),
    returnValueForMissingStub: null,
  );

  @override
  set routePolylines(Set<_i14.Polyline>? value) => super.noSuchMethod(
    Invocation.setter(#routePolylines, value),
    returnValueForMissingStub: null,
  );

  @override
  set transitChangeCircles(Set<_i14.Circle>? value) => super.noSuchMethod(
    Invocation.setter(#transitChangeCircles, value),
    returnValueForMissingStub: null,
  );

  @override
  set showNextClassFab(bool? value) => super.noSuchMethod(
    Invocation.setter(#showNextClassFab, value),
    returnValueForMissingStub: null,
  );

  @override
  set upcomingClass(_i18.AcademicClass? value) =>
      super.noSuchMethod(Invocation.setter(#upcomingClass, value), returnValueForMissingStub: null);

  @override
  set departureMode(_i12.DepartureMode? value) =>
      super.noSuchMethod(Invocation.setter(#departureMode, value), returnValueForMissingStub: null);

  @override
  set selectedDepartureTime(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#selectedDepartureTime, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedArrivalTime(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#selectedArrivalTime, value),
    returnValueForMissingStub: null,
  );

  @override
  set suggestedDepartureTime(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#suggestedDepartureTime, value),
    returnValueForMissingStub: null,
  );

  @override
  set searchResults(List<_i16.SearchSuggestion>? value) =>
      super.noSuchMethod(Invocation.setter(#searchResults, value), returnValueForMissingStub: null);

  @override
  set myLocationEnabled(bool? value) => super.noSuchMethod(
    Invocation.setter(#myLocationEnabled, value),
    returnValueForMissingStub: null,
  );

  @override
  set isSearchBarExpanded(bool? value) => super.noSuchMethod(
    Invocation.setter(#isSearchBarExpanded, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedCampusIndex(int? value) => super.noSuchMethod(
    Invocation.setter(#selectedCampusIndex, value),
    returnValueForMissingStub: null,
  );

  @override
  set cameraTarget(_i17.Coordinate? value) =>
      super.noSuchMethod(Invocation.setter(#cameraTarget, value), returnValueForMissingStub: null);

  @override
  set routeBounds(_i14.LatLngBounds? value) =>
      super.noSuchMethod(Invocation.setter(#routeBounds, value), returnValueForMissingStub: null);

  @override
  set buildingOutlineColor(_i11.Color? color) => super.noSuchMethod(
    Invocation.setter(#buildingOutlineColor, color),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false) as bool);

  @override
  _i9.Future<void> initializeBuildingsData(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#initializeBuildingsData, [path]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> goToCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#goToCurrentLocation, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void toggleCampus() =>
      super.noSuchMethod(Invocation.method(#toggleCampus, []), returnValueForMissingStub: null);

  @override
  void clearCameraTarget() => super.noSuchMethod(
    Invocation.method(#clearCameraTarget, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearRouteBounds() =>
      super.noSuchMethod(Invocation.method(#clearRouteBounds, []), returnValueForMissingStub: null);

  @override
  void updateSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#updateSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSearchResults() => super.noSuchMethod(
    Invocation.method(#clearSearchResults, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearRouteSelection() => super.noSuchMethod(
    Invocation.method(#clearRouteSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  void exitNavigation() =>
      super.noSuchMethod(Invocation.method(#exitNavigation, []), returnValueForMissingStub: null);

  @override
  void setSearchBarExpanded(bool? value) => super.noSuchMethod(
    Invocation.method(#setSearchBarExpanded, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void requestUnfocusSearchBar() => super.noSuchMethod(
    Invocation.method(#requestUnfocusSearchBar, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> selectSearchSuggestion(
    _i16.SearchSuggestion? suggestion,
    _i12.SearchField? field,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectSearchSuggestion, [suggestion, field]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setStartToCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#setStartToCurrentLocation, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void stopLocationTracking() => super.noSuchMethod(
    Invocation.method(#stopLocationTracking, []),
    returnValueForMissingStub: null,
  );

  @override
  void setDepartureMode(_i12.DepartureMode? mode) => super.noSuchMethod(
    Invocation.method(#setDepartureMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void setDepartureTime(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setDepartureTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void setArrivalTime(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setArrivalTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void selectRouteMode(_i15.RouteMode? mode) => super.noSuchMethod(
    Invocation.method(#selectRouteMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> refreshRoutes() =>
      (super.noSuchMethod(
            Invocation.method(#refreshRoutes, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void dispose() =>
      super.noSuchMethod(Invocation.method(#dispose, []), returnValueForMissingStub: null);

  @override
  void notifyLoginSuccess() => super.noSuchMethod(
    Invocation.method(#notifyLoginSuccess, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearLoginSuccessMessage() => super.noSuchMethod(
    Invocation.method(#clearLoginSuccessMessage, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleNextClassFabVisibility(bool? isVisible) => super.noSuchMethod(
    Invocation.method(#toggleNextClassFabVisibility, [isVisible]),
    returnValueForMissingStub: null,
  );

  @override
  void clearUpcomingClass() => super.noSuchMethod(
    Invocation.method(#clearUpcomingClass, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearNextClassDialog() => super.noSuchMethod(
    Invocation.method(#clearNextClassDialog, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> showNextClass() =>
      (super.noSuchMethod(
            Invocation.method(#showNextClass, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []), returnValueForMissingStub: null);
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i3.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_9(this, Invocation.getter(#app)),
          )
          as _i7.FirebaseApp);

  @override
  set app(_i7.FirebaseApp? value) =>
      super.noSuchMethod(Invocation.setter(#app, value), returnValueForMissingStub: null);

  @override
  set tenantId(String? tenantId) =>
      super.noSuchMethod(Invocation.setter(#tenantId, tenantId), returnValueForMissingStub: null);

  @override
  set customAuthDomain(String? customAuthDomain) => super.noSuchMethod(
    Invocation.setter(#customAuthDomain, customAuthDomain),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(Invocation.getter(#pluginConstants), returnValue: <dynamic, dynamic>{})
          as Map<dynamic, dynamic>);

  @override
  _i9.Future<void> useAuthEmulator(String? host, int? port, {bool? automaticHostMapping = true}) =>
      (super.noSuchMethod(
            Invocation.method(
              #useAuthEmulator,
              [host, port],
              {#automaticHostMapping: automaticHostMapping},
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> applyActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#applyActionCode, [code]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.ActionCodeInfo> checkActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#checkActionCode, [code]),
            returnValue: _i9.Future<_i2.ActionCodeInfo>.value(
              _FakeActionCodeInfo_10(this, Invocation.method(#checkActionCode, [code])),
            ),
          )
          as _i9.Future<_i2.ActionCodeInfo>);

  @override
  _i9.Future<void> confirmPasswordReset({required String? code, required String? newPassword}) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {#code: code, #newPassword: newPassword}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<_i3.UserCredential> getRedirectResult() =>
      (super.noSuchMethod(
            Invocation.method(#getRedirectResult, []),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#getRedirectResult, [])),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  bool isSignInWithEmailLink(String? emailLink) =>
      (super.noSuchMethod(
            Invocation.method(#isSignInWithEmailLink, [emailLink]),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Stream<_i3.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i9.Stream<_i3.User?>.empty(),
          )
          as _i9.Stream<_i3.User?>);

  @override
  _i9.Stream<_i3.User?> idTokenChanges() =>
      (super.noSuchMethod(
            Invocation.method(#idTokenChanges, []),
            returnValue: _i9.Stream<_i3.User?>.empty(),
          )
          as _i9.Stream<_i3.User?>);

  @override
  _i9.Stream<_i3.User?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i9.Stream<_i3.User?>.empty(),
          )
          as _i9.Stream<_i3.User?>);

  @override
  _i9.Future<void> sendPasswordResetEmail({
    required String? email,
    _i2.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> sendSignInLinkToEmail({
    required String? email,
    required _i2.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignInLinkToEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [languageCode]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setSettings({
    bool? appVerificationDisabledForTesting = false,
    String? userAccessGroup,
    String? phoneNumber,
    String? smsCode,
    bool? forceRecaptchaFlow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSettings, [], {
              #appVerificationDisabledForTesting: appVerificationDisabledForTesting,
              #userAccessGroup: userAccessGroup,
              #phoneNumber: phoneNumber,
              #smsCode: smsCode,
              #forceRecaptchaFlow: forceRecaptchaFlow,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setPersistence(_i2.Persistence? persistence) =>
      (super.noSuchMethod(
            Invocation.method(#setPersistence, [persistence]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.UserCredential> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#signInAnonymously, [])),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<_i3.UserCredential> signInWithCredential(_i2.AuthCredential? credential) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredential, [credential]),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#signInWithCredential, [credential])),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<_i3.UserCredential> signInWithCustomToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCustomToken, [token]),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#signInWithCustomToken, [token])),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<_i3.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<_i3.UserCredential> signInWithEmailLink({
    required String? email,
    required String? emailLink,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailLink, [], {#email: email, #emailLink: emailLink}),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#signInWithEmailLink, [], {#email: email, #emailLink: emailLink}),
              ),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<_i3.UserCredential> signInWithProvider(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithProvider, [provider]),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#signInWithProvider, [provider])),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<_i3.ConfirmationResult> signInWithPhoneNumber(
    String? phoneNumber, [
    _i3.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i9.Future<_i3.ConfirmationResult>.value(
              _FakeConfirmationResult_4(
                this,
                Invocation.method(#signInWithPhoneNumber, [phoneNumber, verifier]),
              ),
            ),
          )
          as _i9.Future<_i3.ConfirmationResult>);

  @override
  _i9.Future<_i3.UserCredential> signInWithPopup(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPopup, [provider]),
            returnValue: _i9.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(this, Invocation.method(#signInWithPopup, [provider])),
            ),
          )
          as _i9.Future<_i3.UserCredential>);

  @override
  _i9.Future<void> signInWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithRedirect, [provider]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> verifyPasswordResetCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetCode, [code]),
            returnValue: _i9.Future<String>.value(
              _i8.dummyValue<String>(this, Invocation.method(#verifyPasswordResetCode, [code])),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> verifyPhoneNumber({
    String? phoneNumber,
    _i2.PhoneMultiFactorInfo? multiFactorInfo,
    required _i2.PhoneVerificationCompleted? verificationCompleted,
    required _i2.PhoneVerificationFailed? verificationFailed,
    required _i2.PhoneCodeSent? codeSent,
    required _i2.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
    String? autoRetrievedSmsCodeForTesting,
    Duration? timeout = const Duration(seconds: 30),
    int? forceResendingToken,
    _i2.MultiFactorSession? multiFactorSession,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneNumber, [], {
              #phoneNumber: phoneNumber,
              #multiFactorInfo: multiFactorInfo,
              #verificationCompleted: verificationCompleted,
              #verificationFailed: verificationFailed,
              #codeSent: codeSent,
              #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
              #autoRetrievedSmsCodeForTesting: autoRetrievedSmsCodeForTesting,
              #timeout: timeout,
              #forceResendingToken: forceResendingToken,
              #multiFactorSession: multiFactorSession,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> revokeTokenWithAuthorizationCode(String? authorizationCode) =>
      (super.noSuchMethod(
            Invocation.method(#revokeTokenWithAuthorizationCode, [authorizationCode]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> initializeRecaptchaConfig() =>
      (super.noSuchMethod(
            Invocation.method(#initializeRecaptchaConfig, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i2.PasswordValidationStatus> validatePassword(
    _i3.FirebaseAuth? auth,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validatePassword, [auth, password]),
            returnValue: _i9.Future<_i2.PasswordValidationStatus>.value(
              _FakePasswordValidationStatus_11(
                this,
                Invocation.method(#validatePassword, [auth, password]),
              ),
            ),
          )
          as _i9.Future<_i2.PasswordValidationStatus>);
}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i19.GoogleSignIn {
  MockGoogleSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.SignInOption get signInOption =>
      (super.noSuchMethod(Invocation.getter(#signInOption), returnValue: _i20.SignInOption.standard)
          as _i20.SignInOption);

  @override
  List<String> get scopes =>
      (super.noSuchMethod(Invocation.getter(#scopes), returnValue: <String>[]) as List<String>);

  @override
  bool get forceCodeForRefreshToken =>
      (super.noSuchMethod(Invocation.getter(#forceCodeForRefreshToken), returnValue: false)
          as bool);

  @override
  _i9.Stream<_i19.GoogleSignInAccount?> get onCurrentUserChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onCurrentUserChanged),
            returnValue: _i9.Stream<_i19.GoogleSignInAccount?>.empty(),
          )
          as _i9.Stream<_i19.GoogleSignInAccount?>);

  @override
  _i9.Future<_i19.GoogleSignInAccount?> signInSilently({
    bool? suppressErrors = true,
    bool? reAuthenticate = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInSilently, [], {
              #suppressErrors: suppressErrors,
              #reAuthenticate: reAuthenticate,
            }),
            returnValue: _i9.Future<_i19.GoogleSignInAccount?>.value(),
          )
          as _i9.Future<_i19.GoogleSignInAccount?>);

  @override
  _i9.Future<bool> isSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedIn, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<_i19.GoogleSignInAccount?> signIn() =>
      (super.noSuchMethod(
            Invocation.method(#signIn, []),
            returnValue: _i9.Future<_i19.GoogleSignInAccount?>.value(),
          )
          as _i9.Future<_i19.GoogleSignInAccount?>);

  @override
  _i9.Future<_i19.GoogleSignInAccount?> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<_i19.GoogleSignInAccount?>.value(),
          )
          as _i9.Future<_i19.GoogleSignInAccount?>);

  @override
  _i9.Future<_i19.GoogleSignInAccount?> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i9.Future<_i19.GoogleSignInAccount?>.value(),
          )
          as _i9.Future<_i19.GoogleSignInAccount?>);

  @override
  _i9.Future<bool> requestScopes(List<String>? scopes) =>
      (super.noSuchMethod(
            Invocation.method(#requestScopes, [scopes]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<bool> canAccessScopes(List<String>? scopes, {String? accessToken}) =>
      (super.noSuchMethod(
            Invocation.method(#canAccessScopes, [scopes], {#accessToken: accessToken}),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);
}
