// Mocks generated by Mockito 5.4.6 from annotations
// in concordia_campus_guide/test/ui/directions/view_models/directions_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:concordia_campus_guide/domain/interactors/route_interactor.dart'
    as _i3;
import 'package:concordia_campus_guide/domain/models/building.dart' as _i5;
import 'package:concordia_campus_guide/domain/models/coordinate.dart' as _i4;
import 'package:concordia_campus_guide/domain/models/route.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDirectionRoute_0 extends _i1.SmartFake
    implements _i2.DirectionRoute {
  _FakeDirectionRoute_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RouteInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteInteractor extends _i1.Mock implements _i3.RouteInteractor {
  MockRouteInteractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DirectionRoute createOutdoorRoute(
    _i4.Coordinate? currentCoordinate,
    _i5.Building? destination,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createOutdoorRoute, [
              currentCoordinate,
              destination,
            ]),
            returnValue: _FakeDirectionRoute_0(
              this,
              Invocation.method(#createOutdoorRoute, [
                currentCoordinate,
                destination,
              ]),
            ),
          )
          as _i2.DirectionRoute);
}
