// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvzXTT-b4Sy5i0X7W7JqmmGFqAa9LTnHw',
    appId: '1:501981294191:web:8a06ad40bb504a7492279a',
    messagingSenderId: '501981294191',
    projectId: 'concordia-campus-guide',
    authDomain: 'concordia-campus-guide.firebaseapp.com',
    storageBucket: 'concordia-campus-guide.firebasestorage.app',
    measurementId: 'G-4KZB60QVG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCglLyi3JO_-2BFdz-ituHiOTOL5yPY_8Q',
    appId: '1:501981294191:android:8c45c6151630086c92279a',
    messagingSenderId: '501981294191',
    projectId: 'concordia-campus-guide',
    storageBucket: 'concordia-campus-guide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE1OBKkQqMuc8lQX5SZFMrBC87fSmqEyE',
    appId: '1:501981294191:ios:f8a4c8ba16a080c692279a',
    messagingSenderId: '501981294191',
    projectId: 'concordia-campus-guide',
    storageBucket: 'concordia-campus-guide.firebasestorage.app',
    androidClientId:
        '501981294191-foqhoe1c7cvhtco1i0oa2gmk8aljqrp7.apps.googleusercontent.com',
    iosClientId:
        '501981294191-7kq0enh30ba9st8nhup3t5o59h6lmp81.apps.googleusercontent.com',
    iosBundleId: 'com.example.concordiaCampusGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE1OBKkQqMuc8lQX5SZFMrBC87fSmqEyE',
    appId: '1:501981294191:ios:f8a4c8ba16a080c692279a',
    messagingSenderId: '501981294191',
    projectId: 'concordia-campus-guide',
    storageBucket: 'concordia-campus-guide.firebasestorage.app',
    androidClientId:
        '501981294191-foqhoe1c7cvhtco1i0oa2gmk8aljqrp7.apps.googleusercontent.com',
    iosClientId:
        '501981294191-7kq0enh30ba9st8nhup3t5o59h6lmp81.apps.googleusercontent.com',
    iosBundleId: 'com.example.concordiaCampusGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvzXTT-b4Sy5i0X7W7JqmmGFqAa9LTnHw',
    appId: '1:501981294191:web:3e8c8f10970bf88092279a',
    messagingSenderId: '501981294191',
    projectId: 'concordia-campus-guide',
    authDomain: 'concordia-campus-guide.firebaseapp.com',
    storageBucket: 'concordia-campus-guide.firebasestorage.app',
    measurementId: 'G-4WN8ZHBJHM',
  );
}
