// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE48WsdG2F6BIgCcfzWa9bft9YxE7Gf4c',
    appId: '1:910185126084:web:51e49e767fa975fe881191',
    messagingSenderId: '910185126084',
    projectId: 'mini-cap-b97a5',
    authDomain: 'mini-cap-b97a5.firebaseapp.com',
    storageBucket: 'mini-cap-b97a5.firebasestorage.app',
    measurementId: 'G-EFT8RMJ0CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWYyG7VGIdX14y_7faXdo6DEi964tyNfc',
    appId: '1:910185126084:android:e37a418233c93ce1881191',
    messagingSenderId: '910185126084',
    projectId: 'mini-cap-b97a5',
    storageBucket: 'mini-cap-b97a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbsca1J-FwLHV_ZR2r9_-HYwCxdCfGqj4',
    appId: '1:910185126084:ios:35d5c7530af776fd881191',
    messagingSenderId: '910185126084',
    projectId: 'mini-cap-b97a5',
    storageBucket: 'mini-cap-b97a5.firebasestorage.app',
    iosClientId: '910185126084-brp13f61098ujag3nqjdopekslrnv03t.apps.googleusercontent.com',
    iosBundleId: 'com.example.concordiaCampusGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbsca1J-FwLHV_ZR2r9_-HYwCxdCfGqj4',
    appId: '1:910185126084:ios:35d5c7530af776fd881191',
    messagingSenderId: '910185126084',
    projectId: 'mini-cap-b97a5',
    storageBucket: 'mini-cap-b97a5.firebasestorage.app',
    iosClientId: '910185126084-brp13f61098ujag3nqjdopekslrnv03t.apps.googleusercontent.com',
    iosBundleId: 'com.example.concordiaCampusGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE48WsdG2F6BIgCcfzWa9bft9YxE7Gf4c',
    appId: '1:910185126084:web:c1692761da3c73d4881191',
    messagingSenderId: '910185126084',
    projectId: 'mini-cap-b97a5',
    authDomain: 'mini-cap-b97a5.firebaseapp.com',
    storageBucket: 'mini-cap-b97a5.firebasestorage.app',
    measurementId: 'G-X4LY8Y8R8R',
  );
}
