// Mocks generated by Mockito 5.4.6 from annotations
// in concordia_campus_guide/test/domain/interactors/calendar_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:concordia_campus_guide/data/repositories/google_calendar.dart' as _i2;
import 'package:googleapis/calendar/v3.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GoogleCalendarRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleCalendarRepository extends _i1.Mock implements _i2.GoogleCalendarRepository {
  MockGoogleCalendarRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Event>> getUpcomingEvents({
    int? maxResults = 10,
    DateTime? timeMin,
    DateTime? timeMax,
    String? calendarId = 'primary',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingEvents, [], {
              #maxResults: maxResults,
              #timeMin: timeMin,
              #timeMax: timeMax,
              #calendarId: calendarId,
            }),
            returnValue: _i3.Future<List<_i4.Event>>.value(<_i4.Event>[]),
          )
          as _i3.Future<List<_i4.Event>>);

  @override
  _i3.Future<List<_i4.Event>> getEventsInRange({
    required DateTime? startDate,
    required DateTime? endDate,
    String? calendarId = 'primary',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEventsInRange, [], {
              #startDate: startDate,
              #endDate: endDate,
              #calendarId: calendarId,
            }),
            returnValue: _i3.Future<List<_i4.Event>>.value(<_i4.Event>[]),
          )
          as _i3.Future<List<_i4.Event>>);

  @override
  _i3.Future<List<_i4.CalendarListEntry>> getUserCalendars() =>
      (super.noSuchMethod(
            Invocation.method(#getUserCalendars, []),
            returnValue: _i3.Future<List<_i4.CalendarListEntry>>.value(<_i4.CalendarListEntry>[]),
          )
          as _i3.Future<List<_i4.CalendarListEntry>>);
}
