// Mocks generated by Mockito 5.4.6 from annotations
// in concordia_campus_guide/test/domain/interactors/places_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:concordia_campus_guide/data/services/places_service.dart'
    as _i2;
import 'package:concordia_campus_guide/domain/models/coordinate.dart' as _i5;
import 'package:concordia_campus_guide/domain/models/place_suggestion.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PlacesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlacesService extends _i1.Mock implements _i2.PlacesService {
  MockPlacesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PlaceSuggestion>> fetchAutocomplete(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAutocomplete, [input]),
            returnValue: _i3.Future<List<_i4.PlaceSuggestion>>.value(
              <_i4.PlaceSuggestion>[],
            ),
          )
          as _i3.Future<List<_i4.PlaceSuggestion>>);

  @override
  _i3.Future<_i5.Coordinate?> fetchPlaceCoordinate(
    String? placeId, {
    String? fallbackQuery,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchPlaceCoordinate,
              [placeId],
              {#fallbackQuery: fallbackQuery},
            ),
            returnValue: _i3.Future<_i5.Coordinate?>.value(),
          )
          as _i3.Future<_i5.Coordinate?>);
}
