// Mocks generated by Mockito 5.4.6 from annotations
// in concordia_campus_guide/test/ui/auth/widgets/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i17;
import 'dart:ui' as _i16;

import 'package:concordia_campus_guide/domain/interactors/calendar_interactor.dart'
    as _i5;
import 'package:concordia_campus_guide/domain/interactors/directions_interactor.dart'
    as _i4;
import 'package:concordia_campus_guide/domain/interactors/map_data_interactor.dart'
    as _i2;
import 'package:concordia_campus_guide/domain/interactors/places_interactor.dart'
    as _i3;
import 'package:concordia_campus_guide/domain/models/academic_class.dart'
    as _i15;
import 'package:concordia_campus_guide/domain/models/building.dart' as _i9;
import 'package:concordia_campus_guide/domain/models/coordinate.dart' as _i14;
import 'package:concordia_campus_guide/domain/models/place_suggestion.dart'
    as _i13;
import 'package:concordia_campus_guide/domain/models/route_option.dart' as _i11;
import 'package:concordia_campus_guide/domain/models/search_suggestion.dart'
    as _i12;
import 'package:concordia_campus_guide/ui/home/view_models/home_view_model.dart'
    as _i8;
import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i6;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i10;
import 'package:google_sign_in/google_sign_in.dart' as _i18;
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart'
    as _i19;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i20;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMapDataInteractor_0 extends _i1.SmartFake
    implements _i2.MapDataInteractor {
  _FakeMapDataInteractor_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlacesInteractor_1 extends _i1.SmartFake
    implements _i3.PlacesInteractor {
  _FakePlacesInteractor_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectionsInteractor_2 extends _i1.SmartFake
    implements _i4.DirectionsInteractor {
  _FakeDirectionsInteractor_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCalendarInteractor_3 extends _i1.SmartFake
    implements _i5.CalendarInteractor {
  _FakeCalendarInteractor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserMetadata_4 extends _i1.SmartFake implements _i6.UserMetadata {
  _FakeUserMetadata_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_5 extends _i1.SmartFake implements _i7.MultiFactor {
  _FakeMultiFactor_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_6 extends _i1.SmartFake implements _i6.IdTokenResult {
  _FakeIdTokenResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_7 extends _i1.SmartFake
    implements _i7.UserCredential {
  _FakeUserCredential_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_8 extends _i1.SmartFake
    implements _i7.ConfirmationResult {
  _FakeConfirmationResult_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_9 extends _i1.SmartFake implements _i7.User {
  _FakeUser_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeViewModel extends _i1.Mock implements _i8.HomeViewModel {
  MockHomeViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MapDataInteractor get mapInteractor =>
      (super.noSuchMethod(
            Invocation.getter(#mapInteractor),
            returnValue: _FakeMapDataInteractor_0(
              this,
              Invocation.getter(#mapInteractor),
            ),
          )
          as _i2.MapDataInteractor);

  @override
  _i3.PlacesInteractor get placesInteractor =>
      (super.noSuchMethod(
            Invocation.getter(#placesInteractor),
            returnValue: _FakePlacesInteractor_1(
              this,
              Invocation.getter(#placesInteractor),
            ),
          )
          as _i3.PlacesInteractor);

  @override
  _i4.DirectionsInteractor get directionsInteractor =>
      (super.noSuchMethod(
            Invocation.getter(#directionsInteractor),
            returnValue: _FakeDirectionsInteractor_2(
              this,
              Invocation.getter(#directionsInteractor),
            ),
          )
          as _i4.DirectionsInteractor);

  @override
  _i5.CalendarInteractor get calendarInteractor =>
      (super.noSuchMethod(
            Invocation.getter(#calendarInteractor),
            returnValue: _FakeCalendarInteractor_3(
              this,
              Invocation.getter(#calendarInteractor),
            ),
          )
          as _i5.CalendarInteractor);

  @override
  bool get showLoginSuccessMessage =>
      (super.noSuchMethod(
            Invocation.getter(#showLoginSuccessMessage),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, _i9.Building> get buildings =>
      (super.noSuchMethod(
            Invocation.getter(#buildings),
            returnValue: <String, _i9.Building>{},
          )
          as Map<String, _i9.Building>);

  @override
  Set<_i10.Polygon> get buildingOutlines =>
      (super.noSuchMethod(
            Invocation.getter(#buildingOutlines),
            returnValue: <_i10.Polygon>{},
          )
          as Set<_i10.Polygon>);

  @override
  Set<_i10.Marker> get buildingMarkers =>
      (super.noSuchMethod(
            Invocation.getter(#buildingMarkers),
            returnValue: <_i10.Marker>{},
          )
          as Set<_i10.Marker>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isSearchingPlaces =>
      (super.noSuchMethod(
            Invocation.getter(#isSearchingPlaces),
            returnValue: false,
          )
          as bool);

  @override
  bool get isSearchingNearbyPlaces =>
      (super.noSuchMethod(
            Invocation.getter(#isSearchingNearbyPlaces),
            returnValue: false,
          )
          as bool);

  @override
  bool get isResolvingPlace =>
      (super.noSuchMethod(
            Invocation.getter(#isResolvingPlace),
            returnValue: false,
          )
          as bool);

  @override
  bool get isResolvingStartLocation =>
      (super.noSuchMethod(
            Invocation.getter(#isResolvingStartLocation),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoadingRoutes =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingRoutes),
            returnValue: false,
          )
          as bool);

  @override
  Map<_i11.RouteMode, _i11.RouteOption> get routeOptions =>
      (super.noSuchMethod(
            Invocation.getter(#routeOptions),
            returnValue: <_i11.RouteMode, _i11.RouteOption>{},
          )
          as Map<_i11.RouteMode, _i11.RouteOption>);

  @override
  _i11.RouteMode get selectedRouteMode =>
      (super.noSuchMethod(
            Invocation.getter(#selectedRouteMode),
            returnValue: _i11.RouteMode.walking,
          )
          as _i11.RouteMode);

  @override
  Set<_i10.Polyline> get routePolylines =>
      (super.noSuchMethod(
            Invocation.getter(#routePolylines),
            returnValue: <_i10.Polyline>{},
          )
          as Set<_i10.Polyline>);

  @override
  Set<_i10.Circle> get transitChangeCircles =>
      (super.noSuchMethod(
            Invocation.getter(#transitChangeCircles),
            returnValue: <_i10.Circle>{},
          )
          as Set<_i10.Circle>);

  @override
  bool get showNextClassFab =>
      (super.noSuchMethod(
            Invocation.getter(#showNextClassFab),
            returnValue: false,
          )
          as bool);

  @override
  bool get showNextClassDialog =>
      (super.noSuchMethod(
            Invocation.getter(#showNextClassDialog),
            returnValue: false,
          )
          as bool);

  @override
  _i8.DepartureMode get departureMode =>
      (super.noSuchMethod(
            Invocation.getter(#departureMode),
            returnValue: _i8.DepartureMode.now,
          )
          as _i8.DepartureMode);

  @override
  List<_i12.SearchSuggestion> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i12.SearchSuggestion>[],
          )
          as List<_i12.SearchSuggestion>);

  @override
  List<_i13.PlaceSuggestion> get nearbySearchResults =>
      (super.noSuchMethod(
            Invocation.getter(#nearbySearchResults),
            returnValue: <_i13.PlaceSuggestion>[],
          )
          as List<_i13.PlaceSuggestion>);

  @override
  int get nearbySearchResultLimit =>
      (super.noSuchMethod(
            Invocation.getter(#nearbySearchResultLimit),
            returnValue: 0,
          )
          as int);

  @override
  bool get myLocationEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#myLocationEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get isSearchBarExpanded =>
      (super.noSuchMethod(
            Invocation.getter(#isSearchBarExpanded),
            returnValue: false,
          )
          as bool);

  @override
  int get unfocusSearchBarSignal =>
      (super.noSuchMethod(
            Invocation.getter(#unfocusSearchBarSignal),
            returnValue: 0,
          )
          as int);

  @override
  List<_i14.Coordinate> get campuses =>
      (super.noSuchMethod(
            Invocation.getter(#campuses),
            returnValue: <_i14.Coordinate>[],
          )
          as List<_i14.Coordinate>);

  @override
  int get selectedCampusIndex =>
      (super.noSuchMethod(
            Invocation.getter(#selectedCampusIndex),
            returnValue: 0,
          )
          as int);

  @override
  Set<_i10.Marker> get mapMarkers =>
      (super.noSuchMethod(
            Invocation.getter(#mapMarkers),
            returnValue: <_i10.Marker>{},
          )
          as Set<_i10.Marker>);

  @override
  set buildings(Map<String, _i9.Building>? value) => super.noSuchMethod(
    Invocation.setter(#buildings, value),
    returnValueForMissingStub: null,
  );

  @override
  set buildingOutlines(Set<_i10.Polygon>? value) => super.noSuchMethod(
    Invocation.setter(#buildingOutlines, value),
    returnValueForMissingStub: null,
  );

  @override
  set buildingMarkers(Set<_i10.Marker>? value) => super.noSuchMethod(
    Invocation.setter(#buildingMarkers, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentBuilding(_i9.Building? value) => super.noSuchMethod(
    Invocation.setter(#currentBuilding, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set errorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  set generateInfoMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#generateInfoMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  set isSearchingPlaces(bool? value) => super.noSuchMethod(
    Invocation.setter(#isSearchingPlaces, value),
    returnValueForMissingStub: null,
  );

  @override
  set isSearchingNearbyPlaces(bool? value) => super.noSuchMethod(
    Invocation.setter(#isSearchingNearbyPlaces, value),
    returnValueForMissingStub: null,
  );

  @override
  set isResolvingPlace(bool? value) => super.noSuchMethod(
    Invocation.setter(#isResolvingPlace, value),
    returnValueForMissingStub: null,
  );

  @override
  set isResolvingStartLocation(bool? value) => super.noSuchMethod(
    Invocation.setter(#isResolvingStartLocation, value),
    returnValueForMissingStub: null,
  );

  @override
  set searchStartMarker(_i10.Marker? value) => super.noSuchMethod(
    Invocation.setter(#searchStartMarker, value),
    returnValueForMissingStub: null,
  );

  @override
  set searchDestinationMarker(_i10.Marker? value) => super.noSuchMethod(
    Invocation.setter(#searchDestinationMarker, value),
    returnValueForMissingStub: null,
  );

  @override
  set startCoordinate(_i14.Coordinate? value) => super.noSuchMethod(
    Invocation.setter(#startCoordinate, value),
    returnValueForMissingStub: null,
  );

  @override
  set destinationCoordinate(_i14.Coordinate? value) => super.noSuchMethod(
    Invocation.setter(#destinationCoordinate, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedStartLabel(String? value) => super.noSuchMethod(
    Invocation.setter(#selectedStartLabel, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedDestinationLabel(String? value) => super.noSuchMethod(
    Invocation.setter(#selectedDestinationLabel, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingRoutes(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingRoutes, value),
    returnValueForMissingStub: null,
  );

  @override
  set routeErrorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#routeErrorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  set routeOptions(Map<_i11.RouteMode, _i11.RouteOption>? value) =>
      super.noSuchMethod(
        Invocation.setter(#routeOptions, value),
        returnValueForMissingStub: null,
      );

  @override
  set selectedRouteMode(_i11.RouteMode? value) => super.noSuchMethod(
    Invocation.setter(#selectedRouteMode, value),
    returnValueForMissingStub: null,
  );

  @override
  set routePolylines(Set<_i10.Polyline>? value) => super.noSuchMethod(
    Invocation.setter(#routePolylines, value),
    returnValueForMissingStub: null,
  );

  @override
  set transitChangeCircles(Set<_i10.Circle>? value) => super.noSuchMethod(
    Invocation.setter(#transitChangeCircles, value),
    returnValueForMissingStub: null,
  );

  @override
  set showNextClassFab(bool? value) => super.noSuchMethod(
    Invocation.setter(#showNextClassFab, value),
    returnValueForMissingStub: null,
  );

  @override
  set upcomingClass(_i15.AcademicClass? value) => super.noSuchMethod(
    Invocation.setter(#upcomingClass, value),
    returnValueForMissingStub: null,
  );

  @override
  set departureMode(_i8.DepartureMode? value) => super.noSuchMethod(
    Invocation.setter(#departureMode, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedDepartureTime(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#selectedDepartureTime, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedArrivalTime(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#selectedArrivalTime, value),
    returnValueForMissingStub: null,
  );

  @override
  set suggestedDepartureTime(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#suggestedDepartureTime, value),
    returnValueForMissingStub: null,
  );

  @override
  set searchResults(List<_i12.SearchSuggestion>? value) => super.noSuchMethod(
    Invocation.setter(#searchResults, value),
    returnValueForMissingStub: null,
  );

  @override
  set nearbySearchResults(List<_i13.PlaceSuggestion>? value) =>
      super.noSuchMethod(
        Invocation.setter(#nearbySearchResults, value),
        returnValueForMissingStub: null,
      );

  @override
  set nearbySearchResultLimit(int? value) => super.noSuchMethod(
    Invocation.setter(#nearbySearchResultLimit, value),
    returnValueForMissingStub: null,
  );

  @override
  set myLocationEnabled(bool? value) => super.noSuchMethod(
    Invocation.setter(#myLocationEnabled, value),
    returnValueForMissingStub: null,
  );

  @override
  set isSearchBarExpanded(bool? value) => super.noSuchMethod(
    Invocation.setter(#isSearchBarExpanded, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedCampusIndex(int? value) => super.noSuchMethod(
    Invocation.setter(#selectedCampusIndex, value),
    returnValueForMissingStub: null,
  );

  @override
  set cameraTarget(_i14.Coordinate? value) => super.noSuchMethod(
    Invocation.setter(#cameraTarget, value),
    returnValueForMissingStub: null,
  );

  @override
  set routeBounds(_i10.LatLngBounds? value) => super.noSuchMethod(
    Invocation.setter(#routeBounds, value),
    returnValueForMissingStub: null,
  );

  @override
  set buildingOutlineColor(_i16.Color? color) => super.noSuchMethod(
    Invocation.setter(#buildingOutlineColor, color),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i17.Future<void> initializeBuildingsData(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#initializeBuildingsData, [path]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> goToCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#goToCurrentLocation, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void toggleCampus() => super.noSuchMethod(
    Invocation.method(#toggleCampus, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearCameraTarget() => super.noSuchMethod(
    Invocation.method(#clearCameraTarget, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearRouteBounds() => super.noSuchMethod(
    Invocation.method(#clearRouteBounds, []),
    returnValueForMissingStub: null,
  );

  @override
  void setActiveSearchField(_i8.SearchField? field) => super.noSuchMethod(
    Invocation.method(#setActiveSearchField, [field]),
    returnValueForMissingStub: null,
  );

  @override
  void setNearbySearchResultLimit(int? value) => super.noSuchMethod(
    Invocation.method(#setNearbySearchResultLimit, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#updateSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSearchResults() => super.noSuchMethod(
    Invocation.method(#clearSearchResults, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearRouteSelection() => super.noSuchMethod(
    Invocation.method(#clearRouteSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  void exitNavigation() => super.noSuchMethod(
    Invocation.method(#exitNavigation, []),
    returnValueForMissingStub: null,
  );

  @override
  void setSearchBarExpanded(bool? value) => super.noSuchMethod(
    Invocation.method(#setSearchBarExpanded, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void requestUnfocusSearchBar() => super.noSuchMethod(
    Invocation.method(#requestUnfocusSearchBar, []),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Future<void> selectSearchSuggestion(
    _i12.SearchSuggestion? suggestion,
    _i8.SearchField? field,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectSearchSuggestion, [suggestion, field]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> setStartToCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#setStartToCurrentLocation, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void stopLocationTracking() => super.noSuchMethod(
    Invocation.method(#stopLocationTracking, []),
    returnValueForMissingStub: null,
  );

  @override
  void setDepartureMode(_i8.DepartureMode? mode) => super.noSuchMethod(
    Invocation.method(#setDepartureMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void setDepartureTime(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setDepartureTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void setArrivalTime(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setArrivalTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void selectRouteMode(_i11.RouteMode? mode) => super.noSuchMethod(
    Invocation.method(#selectRouteMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Future<void> refreshRoutes() =>
      (super.noSuchMethod(
            Invocation.method(#refreshRoutes, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void onMapCameraMove(_i10.CameraPosition? position) => super.noSuchMethod(
    Invocation.method(#onMapCameraMove, [position]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyLoginSuccess() => super.noSuchMethod(
    Invocation.method(#notifyLoginSuccess, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearLoginSuccessMessage() => super.noSuchMethod(
    Invocation.method(#clearLoginSuccessMessage, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleNextClassFabVisibility(bool? isVisible) => super.noSuchMethod(
    Invocation.method(#toggleNextClassFabVisibility, [isVisible]),
    returnValueForMissingStub: null,
  );

  @override
  void clearNextClassDialog() => super.noSuchMethod(
    Invocation.method(#clearNextClassDialog, []),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Future<void> setDestinationToUpcomingClassBuilding() =>
      (super.noSuchMethod(
            Invocation.method(#setDestinationToUpcomingClassBuilding, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> showNextClass() =>
      (super.noSuchMethod(
            Invocation.method(#showNextClass, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void clearUpcomingClass() => super.noSuchMethod(
    Invocation.method(#clearUpcomingClass, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i18.GoogleSignIn {
  MockGoogleSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.SignInOption get signInOption =>
      (super.noSuchMethod(
            Invocation.getter(#signInOption),
            returnValue: _i19.SignInOption.standard,
          )
          as _i19.SignInOption);

  @override
  List<String> get scopes =>
      (super.noSuchMethod(Invocation.getter(#scopes), returnValue: <String>[])
          as List<String>);

  @override
  bool get forceCodeForRefreshToken =>
      (super.noSuchMethod(
            Invocation.getter(#forceCodeForRefreshToken),
            returnValue: false,
          )
          as bool);

  @override
  _i17.Stream<_i18.GoogleSignInAccount?> get onCurrentUserChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onCurrentUserChanged),
            returnValue: _i17.Stream<_i18.GoogleSignInAccount?>.empty(),
          )
          as _i17.Stream<_i18.GoogleSignInAccount?>);

  @override
  _i17.Future<_i18.GoogleSignInAccount?> signInSilently({
    bool? suppressErrors = true,
    bool? reAuthenticate = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInSilently, [], {
              #suppressErrors: suppressErrors,
              #reAuthenticate: reAuthenticate,
            }),
            returnValue: _i17.Future<_i18.GoogleSignInAccount?>.value(),
          )
          as _i17.Future<_i18.GoogleSignInAccount?>);

  @override
  _i17.Future<bool> isSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedIn, []),
            returnValue: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<_i18.GoogleSignInAccount?> signIn() =>
      (super.noSuchMethod(
            Invocation.method(#signIn, []),
            returnValue: _i17.Future<_i18.GoogleSignInAccount?>.value(),
          )
          as _i17.Future<_i18.GoogleSignInAccount?>);

  @override
  _i17.Future<_i18.GoogleSignInAccount?> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i17.Future<_i18.GoogleSignInAccount?>.value(),
          )
          as _i17.Future<_i18.GoogleSignInAccount?>);

  @override
  _i17.Future<_i18.GoogleSignInAccount?> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i17.Future<_i18.GoogleSignInAccount?>.value(),
          )
          as _i17.Future<_i18.GoogleSignInAccount?>);

  @override
  _i17.Future<bool> requestScopes(List<String>? scopes) =>
      (super.noSuchMethod(
            Invocation.method(#requestScopes, [scopes]),
            returnValue: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<bool> canAccessScopes(
    List<String>? scopes, {
    String? accessToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #canAccessScopes,
              [scopes],
              {#accessToken: accessToken},
            ),
            returnValue: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i7.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified =>
      (super.noSuchMethod(Invocation.getter(#emailVerified), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  _i6.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_4(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i6.UserMetadata);

  @override
  List<_i6.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i6.UserInfo>[],
          )
          as List<_i6.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i20.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  _i7.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_5(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i7.MultiFactor);

  @override
  _i17.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i17.Future<String?>.value(),
          )
          as _i17.Future<String?>);

  @override
  _i17.Future<_i6.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i17.Future<_i6.IdTokenResult>.value(
              _FakeIdTokenResult_6(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i17.Future<_i6.IdTokenResult>);

  @override
  _i17.Future<_i7.UserCredential> linkWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i17.Future<_i7.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i17.Future<_i7.UserCredential>);

  @override
  _i17.Future<_i7.UserCredential> linkWithProvider(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i17.Future<_i7.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i17.Future<_i7.UserCredential>);

  @override
  _i17.Future<_i7.UserCredential> reauthenticateWithProvider(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i17.Future<_i7.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i17.Future<_i7.UserCredential>);

  @override
  _i17.Future<_i7.UserCredential> reauthenticateWithPopup(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i17.Future<_i7.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i17.Future<_i7.UserCredential>);

  @override
  _i17.Future<void> reauthenticateWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<_i7.UserCredential> linkWithPopup(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i17.Future<_i7.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i17.Future<_i7.UserCredential>);

  @override
  _i17.Future<void> linkWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<_i7.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i7.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i17.Future<_i7.ConfirmationResult>.value(
              _FakeConfirmationResult_8(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i17.Future<_i7.ConfirmationResult>);

  @override
  _i17.Future<_i7.UserCredential> reauthenticateWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i17.Future<_i7.UserCredential>.value(
              _FakeUserCredential_7(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i17.Future<_i7.UserCredential>);

  @override
  _i17.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> sendEmailVerification([
    _i6.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<_i7.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i17.Future<_i7.User>.value(
              _FakeUser_9(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i17.Future<_i7.User>);

  @override
  _i17.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> updatePhoneNumber(
    _i6.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i6.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);
}

/// A class which mocks [UserCredential].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCredential extends _i1.Mock implements _i7.UserCredential {
  MockUserCredential() {
    _i1.throwOnMissingStub(this);
  }
}
