// Mocks generated by Mockito 5.4.6 from annotations
// in concordia_campus_guide/test/ui/home/widgets/building_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:concordia_campus_guide/domain/interactors/floorplan_interactor.dart'
    as _i2;
import 'package:concordia_campus_guide/domain/models/floorplan.dart' as _i4;
import 'package:concordia_campus_guide/ui/indoor_map/view_models/indoor_view_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFloorplanInteractor_0 extends _i1.SmartFake
    implements _i2.FloorplanInteractor {
  _FakeFloorplanInteractor_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IndoorViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockIndoorViewModel extends _i1.Mock implements _i3.IndoorViewModel {
  @override
  _i2.FloorplanInteractor get floorplanInteractor =>
      (super.noSuchMethod(
            Invocation.getter(#floorplanInteractor),
            returnValue: _FakeFloorplanInteractor_0(
              this,
              Invocation.getter(#floorplanInteractor),
            ),
            returnValueForMissingStub: _FakeFloorplanInteractor_0(
              this,
              Invocation.getter(#floorplanInteractor),
            ),
          )
          as _i2.FloorplanInteractor);

  @override
  bool get listLoadFailed =>
      (super.noSuchMethod(
            Invocation.getter(#listLoadFailed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get listIsLoading =>
      (super.noSuchMethod(
            Invocation.getter(#listIsLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get loadFailed =>
      (super.noSuchMethod(
            Invocation.getter(#loadFailed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set loadedBuildingId(String? value) => super.noSuchMethod(
    Invocation.setter(#loadedBuildingId, value),
    returnValueForMissingStub: null,
  );

  @override
  set loadedRoomNames(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#loadedRoomNames, value),
    returnValueForMissingStub: null,
  );

  @override
  set listLoadFailed(bool? value) => super.noSuchMethod(
    Invocation.setter(#listLoadFailed, value),
    returnValueForMissingStub: null,
  );

  @override
  set listIsLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#listIsLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set loadedFloorplans(Map<String, _i4.Floorplan>? value) => super.noSuchMethod(
    Invocation.setter(#loadedFloorplans, value),
    returnValueForMissingStub: null,
  );

  @override
  set availableFloors(List<String>? value) => super.noSuchMethod(
    Invocation.setter(#availableFloors, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedFloorplan(_i4.Floorplan? value) => super.noSuchMethod(
    Invocation.setter(#selectedFloorplan, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set loadFailed(bool? value) => super.noSuchMethod(
    Invocation.setter(#loadFailed, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> initializeRoomNames() =>
      (super.noSuchMethod(
            Invocation.method(#initializeRoomNames, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> initializeBuildingFloorplans(String? buildingId) =>
      (super.noSuchMethod(
            Invocation.method(#initializeBuildingFloorplans, [buildingId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<String> sortFloorplanKeys(List<String>? keys) =>
      (super.noSuchMethod(
            Invocation.method(#sortFloorplanKeys, [keys]),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  void resetFloorplanLoadState() => super.noSuchMethod(
    Invocation.method(#resetFloorplanLoadState, []),
    returnValueForMissingStub: null,
  );

  @override
  bool changeFloor(String? floorNumber) =>
      (super.noSuchMethod(
            Invocation.method(#changeFloor, [floorNumber]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
